main: me.santoryuogi.basicessentials.BasicEssentials
version: 1.1
name: SantoryuE

commands:
   tp:
      usage: /<command>
      description: Teleport to a player.
   heal:
      usage: /<command>
      description: Heals a player.
   asreload:
      usage: /<command>
      description: Kicks a player.
   ban:
      usage: /<command>
      description: Bans a player.